---
#
# MIT License
#
# (C) Copyright [2022] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

iuf_version: ^0.1.0
name: uan
description: >
  User Access Nodes (UAN).
version: @product_version@

hooks:
  pre_install_check:
    post:
      script_path: validate-pre-install.sh
  deliver_product:
    post:
      script_path: iuf_hooks/setup_k3s_groups.sh

content:
  docker:
  - path: docker

  helm:
  - path: helm

  loftsman:
  - path: manifests/uan.yaml
    use_manifestgen: true
    deploy: true

  nexus_blob_stores:
    yaml_path: 'nexus-blobstores.yaml'

  nexus_repositories:
    yaml_path: 'nexus-repositories.yaml'

  rpms:
  - path: third-party
    repository_name: uan-@major@.@minor@.@patch@-third-party
    repository_type: raw

  vcs:
    path: vcs

  ims:
    images:
    - path: images/application/@uan_image_name@
      rootfs:
        path: application-@uan_image_version@-@uan_image_arch@.squashfs
        md5sum: @uan_rootfs_md5sum@
      kernel:
        path: @uan_kernel_version@-@uan_image_version@-@uan_image_arch@.kernel
        md5sum: @uan_kernel_md5sum@
      initrd:
        path: initrd.img-@uan_image_version@-@uan_image_arch@.xz
        md5sum: @uan_initrd_md5sum@
