dtr.dev.cray.com:
  tls-verify: true
  images:
    cray/cray-uan-config:
    - 0.1.37-20210429213450+d24d4ba
    cray/cray-uan-image-recipe:
    - 0.1.37-20210429213450+d24d4ba
    cray/cray-product-catalog-update:
    - 0.0.4

