artifactory.algol60.net/uan-docker/stable:
  tls-verify: true
  images:
    cray-uan-config:
    - 0.2.38
    cray-uan-image-recipe:
    - 0.2.38

artifactory.algol60.net/csm-docker/stable:
  tls-verify: true
  images:
    cray-product-catalog-update:
    - 0.4.3
