artifactory.algol60.net/uan-docker/stable:
  tls-verify: true
  images:
    cray-uan-config:
    - 0.3.0

artifactory.algol60.net/csm-docker/stable:
  tls-verify: true
  images:
    cray-product-catalog-update:
    - 1.2.62
