arti.dev.cray.com:
  tls-verify: true
  images:
    uan-docker-stable-local/cray-uan-config:
    - 0.2.24
    uan-docker-stable-local/cray-uan-image-recipe:
    - 0.2.24
    csm-docker-stable-local/cray-product-catalog-update:
    - 0.2.0
