arti.dev.cray.com:
  tls-verify: true
  images:
    uan-docker-stable-local/cray-uan-config:
    - 0.1.39
    uan-docker-stable-local/cray-uan-image-recipe:
    - 0.1.39
    csm-docker-stable-local/cray-product-catalog-update:
    - 0.0.4
